version: "3.0"

services:
    postgres:
        image: "postgres:14.1-alpine"
        restart: always
        ports:
            - "5431:5432"
        volumes:
            - ./pgData:/var/lib/psotgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    my-app:
        depends_on:
            - postgres
        build: .
        entrypoint: ["/bin/bash", "./commands/entry-point.sh"]
        ports:
            - "3000:3000"
        environment:
            DB_HOST_DEV: postgres
        volumes:
            - .:/usr/servercode
